@extends('layouts.app')

@section('title', 'Testimonials — Money Maze')

@section('content')
<section class="simple-page-hero"><div class="container narrow-content"><p class="eyebrow">Testimonials</p><h1>{{ $sc['testimonials.title'] ?? 'What it is like to work together — in clients’ own words.' }}</h1><div class="gold-rule"></div><p>{{ $sc['testimonials.lead'] ?? 'Working with money is rarely just a transaction. It often involves ongoing decisions, sensitive questions and the need for someone dependable on the other side.' }}</p></div></section>
<section class="container section-pad testimonial-layout">@if (count($testimonials ?? []))<div class="testimonial-feature"><div class="stars">{{ str_repeat('★', (int) ($testimonials[0]['rating'] ?? 5)) }}</div><blockquote>“{{ $testimonials[0]['quote'] }}”</blockquote><cite>— {{ $testimonials[0]['author'] }}{{ $testimonials[0]['role'] ? ', '.$testimonials[0]['role'] : '' }}</cite></div><div class="testimonial-list">@foreach (array_slice($testimonials, 1) as $t)<article><div class="stars">{{ str_repeat('★', (int) $t['rating']) }}</div><p>“{{ $t['quote'] }}”</p><cite>— {{ $t['author'] }}{{ $t['role'] ? ', '.$t['role'] : '' }}</cite></article>@endforeach</div></section>@else<section class="container section-pad testimonial-layout"><div class="testimonial-feature"><div class="stars">★★★★★</div><blockquote>“Mitali explains complex financial concepts so simply. Her guidance has helped me make confident and well-informed decisions.”</blockquote><cite>— Rajiv S., Business Owner</cite></div><div class="testimonial-list"><article><div class="stars">★★★★★</div><p>“Professional, approachable and extremely knowledgeable. I truly value her holistic approach to my finances.”</p><cite>— Priya M., HR Professional</cite></article><article><div class="stars">★★★★★</div><p>“The process feels organised and calm. I know what information is needed and what the next step should be.”</p><cite>— Ananya K., Salaried Professional</cite></article><article><div class="stars">★★★★★</div><p>“Clear explanations, practical help and a dependable point of contact. That combination makes a real difference.”</p><cite>— Mehul P., Entrepreneur</cite></article></div></section>@endif
<section class="sage-section section-pad"><div class="container two-column-copy"><div><p class="eyebrow">What I hope the experience reflects</p><h2>Reliability, responsiveness and care.</h2></div><div><p>Every client's need is different — some come for investment support, some for tax or GST work, some for financial documentation, and many for a mix of these over time.</p><p>Beyond technical help, I want clients to feel that their matters are being handled with care and that they have greater confidence in the decisions ahead.</p></div></div></section>
<x-cta-banner title="Looking for support with a financial requirement?" copy="Explore the services I offer, or get in touch directly with what you need." primary="Explore services" primary-route="services" secondary="Get in touch" variant="light" />
@endsection
